version: 2.1

orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  setup-vm:
    executor: python
    steps:
      - checkout
      - ansible/install:
          version: 2.9.6
      - ansible/playbook:
          inventory: ANSIBLE_INVENTORY
          playbook: ci/setup-instance.yaml
          private-key: ANSIBLE_SSH_KEY

  docker-build-and-push:
    working_directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            # docker build --cache-from=app -t app .
            echo true
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e ${DOCKER_HUB_EMAIL} -u ${DOCKER_HUB_USER_ID} -p ${DOCKER_HUB_PWD}
            docker tag app ${DOCKER_HUB_USER_ID}/${DOCKER_IMAGE}:$CIRCLE_BUILD_NUM
            docker tag app ${DOCKER_HUB_USER_ID}/${DOCKER_IMAGE}:latest
            docker push ${DOCKER_HUB_USER_ID}/${DOCKER_IMAGE}:$CIRCLE_BUILD_NUM
            docker push ${DOCKER_HUB_USER_ID}/${DOCKER_IMAGE}:latest

  apply-new-image:
    docker:
      - image: node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Setup env file
          command: |
            cd ci
            cat <<EOF > .env
            APP_IMAGE_NAME=${APP_IMAGE_NAME}
            GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            JWT_SECRET=${JWT_SECRET}
            HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET}
            APP_DOMAIN=${APP_DOMAIN}
            HASURA_DOMAIN=${HASURA_DOMAIN}
            LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
            JWT_PUBLIC=${JWT_PUBLIC}
            EOF
      - run:
          name: Apply docker compose
          run: |
            DOCKER_HOST="ssh://${REMOTE_USER}@${REMOTE_ADDRESS}" docker-compose pull
            DOCKER_HOST="ssh://${REMOTE_USER}@${REMOTE_ADDRESS}" docker-compose up -d

  apply-hasura-migrations:
    docker:
      - image: node:latest
#
#    environment:
#      HASURA_GRAPHQL_ADMIN_SECRET: toto
#      HASURA_GRAPHQL_ENDPOINT: tata
    steps:
      - checkout
      - run: yarn add hasura-cli
      - run: |
          cd hasura
          hasura metadata apply
          hasura migrate apply



workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - setup-vm
      - docker-build-and-push
      - apply-new-image:
          requires:
            - setup-vm
            - docker-build-and-push
      - apply-hasura-migrations:
          requires:
            - apply-new-image