-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."profile" AS
--  SELECT "user".name,
--     "user".image,
--     "user".created_at,
--     "user".id
--    FROM "user";
