import type {NextPage} from 'next'
import Head from 'next/head'
import {ComponentWithAlerts} from "../types/alerts";
import {alert} from "../utils/alert";
import {Button} from "../components/Button";
import {faCoffee} from "@fortawesome/free-solid-svg-icons";

const Home: NextPage<ComponentWithAlerts> = () => {

  const notify = () => {
    alert('INFO', 'Hello World !', 'This is a toast !')
  }


  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <button onClick={notify}>Make me a toast</button>
      <br/>
      <Button icon={faCoffee} variant={'PRIMARY'} className={'my-2'}>Hello world</Button><br/>
      <Button icon={faCoffee} variant={'SECONDARY'} className={'my-2'}>Hello world</Button><br/>
      <Button icon={faCoffee} variant={'SUCCESS'} className={'my-2'}>Hello world</Button><br/>
      <Button icon={faCoffee} variant={'ERROR'} className={'my-2'}>Hello world</Button><br/>
      <Button icon={faCoffee} variant={'WARNING'} className={'my-2'}>Hello world</Button><br/>
      <Button icon={faCoffee} variant={'DISABLED'} className={'my-2'}>Hello world</Button><br/>


    </div>
  )
}

export default Home
