import type { NextPage } from 'next'
import Head from 'next/head'
import {ComponentWithAlerts} from "../types/alerts";
import {alert} from "../utils/alert";

const Home: NextPage<ComponentWithAlerts> = () => {

  const notify = () => {
    alert('INFO', 'Hello World !', 'This is a toast !')
  }



  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={notify}>Make me a toast</button>

    </div>
  )
}

export default Home
