import type {NextPage} from 'next'
import Head from 'next/head'
import {ComponentWithAlerts} from "../types/alerts";
import {alert} from "../utils/alert";
import React from "react";
import {useCurrentUser} from "../hooks/useCurrentUser";

const Home: NextPage<ComponentWithAlerts> = () => {
  const {user, error, fetching} = useCurrentUser();



  const notify = () => {
    alert('INFO', 'Hello World !', 'This is a toast !')
  }


  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <button onClick={notify}>Make me a toast</button>
      <br/>

      <p>Error {JSON.stringify(error)}</p>
      <p>Fetching {JSON.stringify(fetching)}</p>
      <p>User {JSON.stringify(user)}</p>

          {/*Signed in as {session.user?.email} <br/>*/}
          {/*<button onClick={() => signOut()}>Sign out</button>*/}

      {/*{!session && <>*/}
      {/*    Not signed in <br/>*/}
      {/*    <button onClick={() => signIn()}>Sign in</button>*/}
      {/*</>}*/}


    </div>
  )
}

export default Home
