version: "3.9"

services:
  # Web Application
  web:
    image: "${APP_IMAGE_NAME}:latest"
    environment:
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      JWT_SECRET: "${JWT_SECRET}"
      HASURA_ADMIN: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_URL: "http://hasura:8080"
      NEXTAUTH_URL: "${APP_DOMAIN}"
      NEXT_PUBLIC_HASURA_URL: "${HASURA_DOMAIN}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"

  # Traefik
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # Hasura
  hasura:
    image: hasura/graphql-engine:v2.0.9
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: "${JWT_PUBLIC}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${HASURA_DOMAIN}`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"

  # Database
  postgres:
    image: postgres:12
    volumes:
      - hasura_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres



